### ISSUE TITLE
Bug: Added Team (menu item) disappears when navigating to a different page

### ISSUE THREAD

**Issue by waveminded** [quadratichq/quadratic#1122] opened 2024-02-23 21:09 UTC
1. create a new Team
2. add credit card details / subscribe
3. new Team is added to the sidebar
4. click on something like your profile -> new team disappears from sidebar
5. refresh page, new Team reappears again

**Comment by jimniels** [comment] 2024-02-24 15:31
@davidkircos this is a problem with our `filteredTeams` logic when we redirect back from stripe.

`const teamsFiltered = teams.filter((team) => team.team.activated || team.team.uuid === params.uuid);`

The problem is that we navigate back to the team and its value is `activated: false` but because we're on the route, we show it. However, once you navigate away from it, its value is still `activated: false` so now it disappears from the UI. 

Once the user navigates once again to a team, the `/teams` route revalidates and then the data comes back as `activated: true` and that's why it re-appears in the UI.

We will have to re-think this approach.

**Comment by davidkircos** [comment] 2024-02-24 16:09
Yeah, I think this is a relatively low priority. It's an edge case, and fixed by a refresh

**Comment by jimniels** [comment] 2024-02-27 23:36
FWIW: once we ship sockets for updating team data, this should (hopefully) go away — as long as the stripe web hook is fast enough.

**Comment by luke-quadratic** [comment] 2024-06-20 16:54
tested in SQL branch, not relevant with sweeping workspace changes

**Closed by luke-quadratic** 2024-06-20 16:54 UTC
Labels: type: bug, papercut
