### ISSUE TITLE
feature: without interactive colaboration, this app is not useful

### ISSUE THREAD

**Issue by jerzydziewierz** [quadratichq/quadratic#456] opened 2023-05-01 15:46 UTC
Come on,
I have a python box already,
the only reason why I tried this app is to share my results with a friend, interactively, the way that google sheets does it,

and google sheets does support macro writing so it's not like it cannot do computation,s

**Comment by davidkircos** [comment] 2023-05-01 15:47
We hear you. On it.

**Comment by jimniels** [comment] 2023-05-11 20:04
Closing as duplicate of #490

**Closed by jimniels** 2023-05-11 20:04 UTC
