### ISSUE TITLE
Can't render cjk using bitmapText

### ISSUE THREAD

**Issue by ChasLui** [quadratichq/quadratic#107] opened 2022-08-26 02:35 UTC
Can't render cjk using bitmapText

**Comment by davidkircos** [comment] 2022-08-26 03:44
Could you provide more detail about what you are trying to accomplish?

**Comment by ChasLui** [comment] 2022-08-28 07:04
For example, if you enter any Chinese '你好世界' in the cell, it cannot be rendered.

**Comment by davidkircos** [comment] 2022-08-28 15:26
Ah yes, thank you for creating this issue. Quadratic fonts currently only
support ASCII.

**Comment by jimniels** [comment] 2023-05-17 20:05
Closing, as this is a duplicate of #506

**Closed by jimniels** 2023-05-17 20:05 UTC
Labels: duplicate, GL / UI / UX
