### ISSUE TITLE
Hitting escape in code editor does not bring up "unsaved changes" modal

### ISSUE THREAD

**Issue by N-Demir** [quadratichq/quadratic#964] opened 2024-01-05 21:49 UTC
This handy modal for avoiding losing unsaved changes in the code editor does not show up if you hit `esc` on the keyboard instead of pressing the "x"

![Screenshot 2024-01-05 at 1 35 11 PM](https://github.com/quadratichq/quadratic/assets/23620644/a9a3f5f0-adb3-4cbf-bad3-2506096fbd72)

Pretty unfortunate to lose work that way since it wasn't being auto-saved : (

**Comment by luke-quadratic** [comment] 2024-01-05 22:34
Hey thanks for the heads up, it's good to hear feedback multiple times so we can really bump it up as a priority; this is a duplicate of a high priority issue that is in the queue to be worked on - #907.

**Closed by luke-quadratic** 2024-01-05 22:34 UTC
