### ISSUE TITLE
Copy Paste Error

### ISSUE THREAD

**Issue by samzer** [quadratichq/quadratic#55] opened 2022-04-24 06:12 UTC
# Bug

## What is the issue?
Copy pasting a group of cells results in error page

## How to reproduce the issue?
Copy paste any cells that contains the table data and paste it in an empty location.

## What are the environment details?
OS: macOS Monetery 12.0.1
System: Macbook M1 Pro 2021
node version: 10.15.1
npm version: 7.24.2
browser: Firefox 99.0.1

## Screenshots
<img width="1244" alt="Screen Shot 2022-04-24 at 11 41 55" src="https://user-images.githubusercontent.com/1539703/164959270-16bde9f7-3d44-4262-8943-c4c7c7d63dad.png">

**Comment by davidkircos** [comment] 2022-04-24 23:35
Thanks @samzer i believe this is related to Firefox having a different api for copy paste functions. To double check. Could you share a sample of the data you were attempting to paste?

**Comment by samzer** [comment] 2022-04-25 09:23
Sure, attaching a video below

https://user-images.githubusercontent.com/1539703/165060369-0140795a-38d7-4d0d-9871-ecab27c29a6f.mov

I believe this is the default sample data ( powered by pandas random data generator) that comes with the repo.

.

**Comment by davidkircos** [comment] 2022-05-03 01:04
@samzer This is caused by `navigator.clipboard` requires a secure origin (HTTPS)

See: https://stackoverflow.com/a/51823007/1805218

Marking as "wont fix"

**Closed** 2022-05-03 01:04 UTC
Labels: bug, wontfix
